In [1]:
import pandas as pd
df= pd.read_excel(r"C:\ML_Final_Project\notebooks\Data\OnlineKhabar_Posts_Final.xlsx")
df.head()

,Posts,URL
0,"HoR passes Finance Bill, 2083",{'url': 'https://english.onlinekhabar.com/hor-...
1,HoR passes Bill to Raise Public Debt,{'url': 'https://english.onlinekhabar.com/hor-...
2,49 of RSP’s 99 elected central members are wom...,{'url': 'https://english.onlinekhabar.com/49-r...
3,Who is to blame for the chaos at RSP’s convent...,{'url': 'https://english.onlinekhabar.com/chao...
4,RSP promised a smarter convention than its riv...,{'url': 'https://english.onlinekhabar.com/rsp-...

In [2]:
import ast
df["URL"] = df["URL"].apply(ast.literal_eval)
df["Category"] = df["URL"].apply(lambda x: x["category"])
df["Link"] = df["URL"].apply(lambda x: x["url"])

In [3]:
df.head()

,Posts,URL,Category,Link
0,"HoR passes Finance Bill, 2083",{'url': 'https://english.onlinekhabar.com/hor-...,Politics,https://english.onlinekhabar.com/hor-passes-fi...
1,HoR passes Bill to Raise Public Debt,{'url': 'https://english.onlinekhabar.com/hor-...,Politics,https://english.onlinekhabar.com/hor-passes-bi...
2,49 of RSP’s 99 elected central members are wom...,{'url': 'https://english.onlinekhabar.com/49-r...,Politics,https://english.onlinekhabar.com/49-rsps-centr...
3,Who is to blame for the chaos at RSP’s convent...,{'url': 'https://english.onlinekhabar.com/chao...,Politics,https://english.onlinekhabar.com/chaos-at-rsps...
4,RSP promised a smarter convention than its riv...,{'url': 'https://english.onlinekhabar.com/rsp-...,Politics,https://english.onlinekhabar.com/rsp-promised-...

In [4]:
df.shape

(12394, 4)